import type { Product, Order, Farmer, Subscription } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "p001",
    name: "Organic Tomatoes",
    price: 3.99,
    unit: "lb",
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1518977822534-7049a61ee0c2?w=400&q=80",
    farmer: "Robert Green",
    farmerId: "farm-001",
    organic: true,
    freshness: "ultra-fresh",
    stock: 50,
    rating: 4.8,
    reviews: 124,
    description: "Vine-ripened organic tomatoes harvested this morning from our family farm.",
    harvestDate: "2026-04-16",
  },
  {
    id: "p002",
    name: "Fresh Carrots",
    price: 2.49,
    unit: "bunch",
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1447175008436-054170c2e979?w=400&q=80",
    farmer: "Mary Fields",
    farmerId: "farm-002",
    organic: true,
    freshness: "fresh",
    stock: 80,
    rating: 4.6,
    reviews: 89,
    description: "Sweet, crunchy carrots pulled from rich soil this week.",
    harvestDate: "2026-04-14",
  },
  {
    id: "p003",
    name: "Strawberries",
    price: 5.99,
    unit: "pint",
    category: "Fruits",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80",
    farmer: "John Berry",
    farmerId: "farm-003",
    organic: false,
    freshness: "ultra-fresh",
    stock: 30,
    rating: 4.9,
    reviews: 201,
    description: "Sun-kissed strawberries bursting with natural sweetness.",
    harvestDate: "2026-04-16",
    discount: 10,
  },
  {
    id: "p004",
    name: "Farm Fresh Eggs",
    price: 6.49,
    unit: "dozen",
    category: "Dairy & Eggs",
    image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&q=80",
    farmer: "Robert Green",
    farmerId: "farm-001",
    organic: true,
    freshness: "fresh",
    stock: 100,
    rating: 4.7,
    reviews: 156,
    description: "Free-range eggs from happy hens with rich golden yolks.",
    harvestDate: "2026-04-15",
  },
  {
    id: "p005",
    name: "Raw Honey",
    price: 12.99,
    unit: "jar",
    category: "Natural",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&q=80",
    farmer: "Bee Haven Farm",
    farmerId: "farm-004",
    organic: true,
    freshness: "fresh",
    stock: 25,
    rating: 5.0,
    reviews: 78,
    description: "Pure wildflower honey collected from our own hive colonies.",
    harvestDate: "2026-04-01",
  },
  {
    id: "p006",
    name: "Spinach",
    price: 3.49,
    unit: "bag",
    category: "Leafy Greens",
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80",
    farmer: "Mary Fields",
    farmerId: "farm-002",
    organic: true,
    freshness: "ultra-fresh",
    stock: 60,
    rating: 4.5,
    reviews: 67,
    description: "Baby spinach leaves, tender and vibrant, picked at peak freshness.",
    harvestDate: "2026-04-16",
  },
  {
    id: "p007",
    name: "Blueberries",
    price: 7.99,
    unit: "pint",
    category: "Fruits",
    image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&q=80",
    farmer: "Blue Ridge Farm",
    farmerId: "farm-005",
    organic: false,
    freshness: "fresh",
    stock: 40,
    rating: 4.7,
    reviews: 113,
    description: "Plump, juicy blueberries from mountain farm elevations.",
    harvestDate: "2026-04-13",
    discount: 15,
  },
  {
    id: "p008",
    name: "Whole Milk",
    price: 4.99,
    unit: "gallon",
    category: "Dairy & Eggs",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80",
    farmer: "Cloverdale Dairy",
    farmerId: "farm-006",
    organic: true,
    freshness: "fresh",
    stock: 45,
    rating: 4.6,
    reviews: 92,
    description: "Non-homogenized whole milk from grass-fed cows.",
    harvestDate: "2026-04-15",
  },
  {
    id: "p009",
    name: "Zucchini",
    price: 2.99,
    unit: "lb",
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1563252722-6434563a985d?w=400&q=80",
    farmer: "Robert Green",
    farmerId: "farm-001",
    organic: false,
    freshness: "good",
    stock: 70,
    rating: 4.4,
    reviews: 45,
    description: "Tender summer zucchini, perfect for grilling or baking.",
    harvestDate: "2026-04-12",
  },
  {
    id: "p010",
    name: "Apples (Honeycrisp)",
    price: 4.49,
    unit: "lb",
    category: "Fruits",
    image: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80",
    farmer: "Sunrise Orchard",
    farmerId: "farm-007",
    organic: true,
    freshness: "fresh",
    stock: 90,
    rating: 4.8,
    reviews: 187,
    description: "Crispy, sweet Honeycrisp apples from our century-old orchard.",
    harvestDate: "2026-04-10",
    discount: 5,
  },
  {
    id: "p011",
    name: "Kale Bunch",
    price: 2.79,
    unit: "bunch",
    category: "Leafy Greens",
    image: "https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=400&q=80",
    farmer: "Mary Fields",
    farmerId: "farm-002",
    organic: true,
    freshness: "ultra-fresh",
    stock: 55,
    rating: 4.5,
    reviews: 61,
    description: "Nutrient-dense curly kale harvested at the peak of flavor.",
    harvestDate: "2026-04-16",
  },
  {
    id: "p012",
    name: "Butter (Artisan)",
    price: 8.99,
    unit: "block",
    category: "Dairy & Eggs",
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&q=80",
    farmer: "Cloverdale Dairy",
    farmerId: "farm-006",
    organic: true,
    freshness: "fresh",
    stock: 30,
    rating: 4.9,
    reviews: 73,
    description: "Cultured artisan butter churned from cream of grass-fed cows.",
    harvestDate: "2026-04-14",
  },
];

export const ORDERS: Order[] = [
  {
    id: "ORD-001",
    customerId: "cust-001",
    customerName: "Alex Johnson",
    items: [
      { product: PRODUCTS[0], quantity: 2 },
      { product: PRODUCTS[3], quantity: 1 },
    ],
    total: 14.47,
    status: "delivered",
    date: "2026-04-10",
    deliveryAddress: "123 Main St, Springfield",
    farmerId: "farm-001",
    deliveryPartnerId: "del-001",
  },
  {
    id: "ORD-002",
    customerId: "cust-001",
    customerName: "Alex Johnson",
    items: [
      { product: PRODUCTS[2], quantity: 1 },
      { product: PRODUCTS[4], quantity: 1 },
    ],
    total: 18.98,
    status: "in-transit",
    date: "2026-04-15",
    deliveryAddress: "123 Main St, Springfield",
    farmerId: "farm-003",
    deliveryPartnerId: "del-001",
  },
  {
    id: "ORD-003",
    customerId: "cust-002",
    customerName: "Lisa Park",
    items: [{ product: PRODUCTS[1], quantity: 3 }],
    total: 7.47,
    status: "confirmed",
    date: "2026-04-16",
    deliveryAddress: "789 Oak Ave, Portland",
    farmerId: "farm-002",
    deliveryPartnerId: "del-001",
  },
  {
    id: "ORD-004",
    customerId: "cust-003",
    customerName: "Tom Rivera",
    items: [
      { product: PRODUCTS[6], quantity: 2 },
      { product: PRODUCTS[9], quantity: 1 },
    ],
    total: 20.47,
    status: "pending",
    date: "2026-04-16",
    deliveryAddress: "321 Elm St, Austin",
  },
];

export const FARMERS: Farmer[] = [
  {
    id: "farm-001",
    name: "Robert Green",
    email: "farmer@test.com",
    farm: "Sunny Acres Farm",
    location: "Vermont, USA",
    approved: true,
    products: 8,
    earnings: 4280,
    joinedAt: "2023-08-20",
    story: "Three generations of sustainable farming. We believe in working with nature, not against it.",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
  },
  {
    id: "farm-002",
    name: "Mary Fields",
    email: "mary@fields.com",
    farm: "Green Valley Gardens",
    location: "California, USA",
    approved: true,
    products: 12,
    earnings: 6150,
    joinedAt: "2023-06-15",
    story: "Organic pioneer for 20 years. Every vegetable is grown with love and zero pesticides.",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
  },
  {
    id: "farm-003",
    name: "John Berry",
    email: "john@berry.com",
    farm: "Berry Bliss Farm",
    location: "Oregon, USA",
    approved: true,
    products: 6,
    earnings: 3890,
    joinedAt: "2024-01-10",
    story: "Specializing in heritage berry varieties you won't find in any grocery store.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
  },
  {
    id: "farm-004",
    name: "Bee Haven Farm",
    email: "bees@haven.com",
    farm: "Bee Haven Apiary",
    location: "Montana, USA",
    approved: false,
    products: 3,
    earnings: 1200,
    joinedAt: "2026-04-01",
    story: "We tend to over 200 hives and produce the purest wildflower honey in the state.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
  },
];

export const SUBSCRIPTIONS: Subscription[] = [
  {
    id: "sub-basic",
    name: "Seedling",
    price: 29.99,
    duration: "weekly",
    items: ["5 vegetables", "2 fruits", "1 herb bunch"],
    description: "Perfect for individuals and couples. Fresh basics every week.",
  },
  {
    id: "sub-family",
    name: "Harvest",
    price: 54.99,
    duration: "weekly",
    items: ["8 vegetables", "4 fruits", "2 herb bunches", "1 dozen eggs"],
    description: "Ideal for families. More variety, more freshness.",
    popular: true,
  },
  {
    id: "sub-premium",
    name: "Abundance",
    price: 89.99,
    duration: "weekly",
    items: ["12 vegetables", "6 fruits", "3 herb bunches", "2 dozen eggs", "Seasonal specials"],
    description: "The complete farm experience with seasonal surprises.",
  },
  {
    id: "sub-monthly",
    name: "Farm Partner",
    price: 199.99,
    duration: "monthly",
    items: ["Full monthly veggie box", "Premium fruits", "Dairy selection", "Pantry staples", "Free delivery"],
    description: "Commit monthly, save more. The ultimate farm partnership.",
  },
];
